# Generated by Django 5.2.4 on 2025-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('로맨스', '로맨스'), ('코미디', '코미디'), ('액션', '액션'), ('스릴러', '스릴러'), ('애니메이션', '애니메이션'), ('SF', 'SF'), ('드라마', '드라마'), ('기타', '기타')], max_length=50, verbose_name='장르'),
        ),
    ]
